### ISSUE TITLE
Error in the    createradfile(scene, frame, self, self.simnode) in vi_operators.py

### ISSUE THREAD

**Issue by olemariussvendsen** [rgsouthall/vi-suite07#15] opened 2024-01-24 13:20 UTC
Afternoon Ryan, i hope you are doing well.

I finally have an actual project we are to use the glare module we discussed before Christmas. However,  i am experiencing some issues. My blender file is in the link below, and i have made sure to edit out all "/" annotation from the file. 
https://we.tl/t-Wf3p7FOZ2Q

I have made sure to delete the Vi-suite completely from the appdata file location. Reinstalled even. What is confusing i have a set with different files i played around with before Christmas which i can still use and even run without any problem. With the file i have send you, i get an error with the  "createradfile(scene, frame, self, self.simnode)" part of your code. If you kindly have a bit of time to overlook, what have i done inaccurately? I am trying first and formost to use the preview camera before running any simulations. Would it be some other non functional notations i can not use? I have even tried to remove all use of the norwegian letters æ, ø and å.

Python: Traceback (most recent call last):
  File "C:\Users\OleMariusSvendsen\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\vi-suite07-master\vi_operators.py", line 1096, in invoke
    createradfile(scene, frame, self, self.simnode)
  File "C:\Users\OleMariusSvendsen\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\vi-suite07-master\livi_export.py", line 419, in createradfile
    elif frame < min([int(k) for k in link.from_node['Text'].keys()]):
ValueError: min() arg is an empty sequence

**Comment by rgsouthall** [comment] 2024-01-24 13:50
Hi Ole.
Belated Happy New Year.
Works for me on Linux. The Geometry node is red in the file you sent me which means geometry has not been exported or options are out of date. Just want to confirm you have exported the geometry before I do any further debugging.
![Screenshot_20240124_134712](https://github.com/rgsouthall/vi-suite07/assets/1895282/a8f3c38f-29c6-4096-8803-ddcbc024c2c5)

**Comment by rgsouthall** [comment] 2024-01-24 13:57
I get your error if I do not export the geometry and I note you are on Blender frame 203. Could be that you exported the Context on one frame and the geometry on another. Make sure you export everything on the same frame and I would suggest sticking to frame 1 for static analyses.

**Comment by olemariussvendsen** [comment] 2024-01-24 14:04
Likewise! I hope you had a lovely time with your loved ones.

With Windows 10, i can not run the file. As you had success with it, i downloaded the file i sent to you to just see if it would do anything different. 

With respect to export geometry and frame i do fall a bit short as to what you are referring to here. I am still in a learning process as to what the different part of blender is, and how they work.

**Comment by olemariussvendsen** [comment] 2024-01-24 14:06
And by export, do you mean in the livi geometry, then yes i have pushed that button

**Comment by rgsouthall** [comment] 2024-01-24 14:12
Then reshare the blend file with the LiVi Geometry exported.

**Comment by olemariussvendsen** [comment] 2024-01-24 14:15
NEw link:

https://we.tl/t-ElHiIs6Lpx

**Comment by rgsouthall** [comment] 2024-01-24 14:25
The LiVi Geometry node is still red when I open it. Can you absolutely confirm that your LiVi Geometry node is not red or if it stays red even after you have pressed the geometry export button can you open the windows terminal with the "Window > Toggle system console" blender menu option and paste here any messages you get when you press the geometry export button. Also paste here the contents of the vi-suite-log file in Blender's text editor.

**Comment by olemariussvendsen** [comment] 2024-01-24 14:37
-----

Read prefs: "C:\Users\OleMariusSvendsen\AppData\Roaming\Blender Foundation\Blender\4.0\config\userpref.blend"
register_class(...):
Warning: 'bc.main_panel' does not contain '_PT_' with prefix and suffix
register_class(...):
Warning: 'bc.repair_panel' does not contain '_PT_' with prefix and suffix
register_class(...):
Warning: 'bc.limdiss_panel' does not contain '_PT_' with prefix and suffix
register_class(...):
Warning: 'bc.topology_panel' does not contain '_PT_' with prefix and suffix
register_class(...):
Warning: 'bc.normals_panel' does not contain '_PT_' with prefix and suffix
register_class(...):
Warning: 'bc.objectdata_panel' does not contain '_PT_' with prefix and suffix
CAD_Sketcher-main:{INFO}: Logging into: C:\Users\OLEMAR~1\AppData\Local\Temp\CAD_Sketcher-main-OleMariusSvendsen.log
15:26:38.302 [INFO ] sverchok core\__init__.py:150 - Initializing Sverchok logging (level=INFO). Blender version=4.0.1, Sverchok version=v1.3.0-alpha
 ______ _    _ _______  ______ _______ _     _  _____  _     _
/______  \  /  |______ |_____/ |       |_____| |     | |____/
______/   \/   |______ |    \_ |_____  |     | |_____| |    \_
initialized.
Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 4.0\4.0\scripts\modules\addon_utils.py", line 364, in enable
    mod = importlib.import_module(module_name)
  File "C:\Program Files\Blender Foundation\Blender 4.0\4.0\python\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\OleMariusSvendsen\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\slcad_transform\__init__.py", line 63, in <module>
    from .slcad_transform import register, unregister
  File "C:\Users\OleMariusSvendsen\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\slcad_transform\slcad_transform.py", line 45, in <module>
    from .utils.gpu_draw import (
  File "C:\Users\OleMariusSvendsen\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\slcad_transform\utils\gpu_draw.py", line 401, in <module>
    class GPU_2d_uniform(GPU_Draw):
  File "C:\Users\OleMariusSvendsen\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\slcad_transform\utils\gpu_draw.py", line 402, in GPU_2d_uniform
    _shader = get_shader('2D_UNIFORM_COLOR')
  File "C:\Users\OleMariusSvendsen\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\slcad_transform\utils\gpu_draw.py", line 85, in get_shader
    return gpu.shader.from_builtin(builtin_typ)
ValueError: expected a string in ('FLAT_COLOR', 'IMAGE', 'IMAGE_COLOR', 'SMOOTH_COLOR', 'UNIFORM_COLOR', 'POLYLINE_FLAT_COLOR', 'POLYLINE_SMOOTH_COLOR', 'POLYLINE_UNIFORM_COLOR'), got '2D_UNIFORM_COLOR'
Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 4.0\4.0\scripts\modules\addon_utils.py", line 364, in enable
    mod = importlib.import_module(module_name)
  File "C:\Program Files\Blender Foundation\Blender 4.0\4.0\python\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\OleMariusSvendsen\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\blenderbim_spreadsheet\__init__.py", line 20, in <module>
    from . import operator, ui, prop
  File "C:\Users\OleMariusSvendsen\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\blenderbim_spreadsheet\operator.py", line 14, in <module>
    import pandas as pd
  File "C:\Users\OleMariusSvendsen\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\blenderbim_spreadsheet\libs\site\packages\pandas\__init__.py", line 16, in <module>
    raise ImportError(
ImportError: Unable to import required dependencies:
dateutil: No module named 'dateutil'
System PySide6 not found
System Matplotlib not found
System Kivy not found
Setting library paths
qt.qpa.window: SetProcessDpiAwarenessContext() failed: The operation completed successfully.
Qt's default DPI awareness context is DPI_AWARENESS_CONTEXT_PER_MONITOR_AWARE_V2. If you know what you are doing, you can overwrite this default using qt.conf (https://doc.qt.io/qt-6/highdpi.html#configuring-windows).
VI-Suite: Using built-in libraries
'docker' is not recognized as an internal or external command,
operable program or batch file.
No psutil: No module named 'psutil'
Warning: addon-module add_mesh_extra_objects found module but without '__addon_enabled__' field, possible name collision from file: 'C:\\Program Files\\Blender Foundation\\Blender 4.0\\4.0\\scripts\\addons\\add_mesh_extra_objects\\__init__.py'
Read blend: "C:\Users\OleMariusSvendsen\Downloads\Sandens K11\Sandens K11 Blender_format.blend"
Error: Python: Traceback (most recent call last):
  File "C:\Users\OleMariusSvendsen\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\vi-suite07-master\vi_operators.py", line 765, in execute
    radgexport(self, node)
  File "C:\Users\OleMariusSvendsen\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\vi-suite07-master\livi_export.py", line 209, in radgexport
    gradfile += bmesh2mesh(scene, bm, o, frame, tempmatfilename, node.mesh, node.triangulate)
  File "C:\Users\OleMariusSvendsen\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\vi-suite07-master\livi_export.py", line 71, in bmesh2mesh
    if not m_export and not any([slot.material.vi_params.radtex for slot in oms if slot.material]) and not o.data.polygons[0].use_smooth:
IndexError: bpy_prop_collection[index]: index 0 out of range, size 0

-----


From the VI Suite log, i can read it gives an error due to the "/". However, when i search for that sign, i can not find any object with it.

[VI-suit log.txt](https://github.com/rgsouthall/vi-suite07/files/14039763/VI-suit.log.txt)

**Comment by rgsouthall** [comment] 2024-01-24 14:54
Ah. I think you have a mesh object with no data in it. I have committed a change to master that should fix it.

**Comment by olemariussvendsen** [comment] 2024-01-24 15:12
I am happy to share that the fix resolved it. I take it when i run a preview with low setting, i get a simplified results compared to your image which has much higher details? OR did you run a preview which was not DF Sky?


![2024-01-24_16-04-45](https://github.com/rgsouthall/vi-suite07/assets/135004477/80f90521-f633-4eae-b704-8b214b76b14d)

**Comment by rgsouthall** [comment] 2024-01-24 15:29
This is now not a bug report so would prefer for this to go to the google group.

**Comment by olemariussvendsen** [comment] 2024-01-24 15:31
Agreed

**Comment by rgsouthall** [comment] 2024-01-24 15:35
Closing this as appears to be fixed.

**Closed as completed by rgsouthall** 2024-01-24 15:35 UTC
